5350 Thesis in Economics

Andres Cruz 25199 & Klara Holmer 25037 

Code for Grundskola and Gymnasieskola

In [177]:
# Importing Libraries
import numpy as np 
import pandas as pd 
import glob
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [178]:
# Step 1 - Importing ExcelFiles and Concatenating DataFrames

# --- Gymnasieskola  Årskurs 1 or Upper Secondary School Year 10 --- 

# Defining the full path to the Excel file in the new folder
pathname = '/Users/andrescruz/Documents/Handelshögskolan/MSc Economic/Semester 4/5350 Thesis in Economics/Processed Data/Gymnasieskola_Data.xlsx'

# Read all sheets at once into a dictionary
sheets = ['English', 'Mathematics', 'Swedish']
gymnasieskola_data = pd.read_excel(pathname, sheet_name=sheets)

# Unpack the dictionary into separate variables if needed
gymnasieskola_data_english = gymnasieskola_data['English']
gymnasieskola_data_mathematics = gymnasieskola_data['Mathematics']
gymnasieskola_data_swedish = gymnasieskola_data['Swedish']

# --- Lower Secondary School Year 9 --- 

# Defining the full path to the Excel file in the new folder
pathname = '/Users/andrescruz/Documents/Handelshögskolan/MSc Economic/Semester 4/5350 Thesis in Economics/Processed Data/Grundskola_Data.xlsx'

# Read all sheets at once into a dictionary
sheets = ['English', 'Mathematics', 'Swedish']
grundskola_data = pd.read_excel(pathname, sheet_name=sheets)

# Unpack the dictionary into separate variables if needed
grundskola_data_english = grundskola_data['English']
grundskola_data_mathematics = grundskola_data['Mathematics']
grundskola_data_swedish_data = grundskola_data['Swedish']

# --- Concatenating --- 

# Engelska
school_data_english = pd.concat([gymnasieskola_data_english, grundskola_data_english], ignore_index=True)

# Matematik
school_data_mathematics = pd.concat([gymnasieskola_data_mathematics, grundskola_data_mathematics], ignore_index=True)

# Svenska
school_data_swedish = pd.concat([gymnasieskola_data_swedish, grundskola_data_swedish_data], ignore_index=True)

# List of DataFrames
dataframes = [school_data_english, school_data_mathematics, school_data_swedish]

school_data_swedish

,school_ID,school_municipality,municipality_ID,type_of_ownership,academic_year,educational_stage,school_size,total_school_students,graduating_students,graduates_average_grade_points,...,share_foreign_background,share_postsecondary_parents,total_fulltime_teachers,total_fulltime_certified_teachers,share_fulltime_certified_teachers,total_active_teachers,total_active_certified_teachers,share_active_certified_teachers,share_students_A_E_sv,share_students_F_sv
0,74776778,Alingsås,1489,Kommunal,2014/15,gymnasieskola,100-199,135.0,44.0,14.7,...,19.0,46.0,7.7,6.1,78.8,20.0,15.0,75.0,100.0,0.0
1,18345915,Alingsås,1489,Kommunal,2014/15,gymnasieskola,200-299,211.0,41.0,15.2,...,16.0,67.0,14.2,13.8,97.2,29.0,27.0,93.1,100.0,0.0
2,68229719,Alingsås,1489,Kommunal,2014/15,gymnasieskola,100-199,155.0,45.0,14.8,...,14.0,53.0,13.1,12.6,95.9,23.0,21.0,91.3,100.0,0.0
3,61004230,Alingsås,1489,Kommunal,2014/15,gymnasieskola,50-99,94.0,44.0,16.5,...,NaN,62.0,8.8,6.0,68.3,16.0,12.0,75.0,100.0,0.0
4,71262305,Arboga,1984,Kommunal,2014/15,gymnasieskola,100-199,183.0,63.0,15.5,...,13.0,68.0,23.2,15.9,68.4,27.0,19.0,70.4,100.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19344,50308658,Överkalix,2513,Kommunal,2021/22,grundskola,100-199,118.0,16.0,11.4,...,25.0,38.0,14.8,7.9,53.0,19.0,11.0,57.9,68.8,31.2
19345,13342436,Överkalix,2513,Enskild,2021/22,grundskola,50-99,54.0,NaN,NaN,...,NaN,41.0,6.1,1.7,27.6,7.0,5.0,71.4,NaN,NaN
19346,46252858,Övertorneå,2518,Enskild,2021/22,grundskola,50-99,62.0,11.0,15.2,...,19.0,53.0,6.9,2.3,33.2,10.0,4.0,40.0,100.0,0.0
19347,90707437,Övertorneå,2518,Kommunal,2021/22,grundskola,50-99,72.0,12.0,13.5,...,18.0,50.0,7.9,3.6,45.4,16.0,10.0,62.5,100.0,0.0
19348,18991431,Övertorneå,2518,Kommunal,2021/22,grundskola,100-199,147.0,25.0,12.1,...,28.0,37.0,15.6,12.0,76.9,24.0,20.0,83.3,96.0,4.0

In [179]:
# Step 2 -  Adding County ID 

# Defining the full path to the Excel file in the new folder
pathname = '/Users/andrescruz/Documents/Handelshögskolan/MSc Economic/Semester 4/5350 Thesis in Economics/Raw Data/Kommun Data/georef-sweden-kommun.xlsx'

# Read all sheets at once into a dictionary
kommun_data = pd.read_excel(pathname, sheet_name=0)

# List of new names 
new_names = [
    'geo_point',            # Column 1 Geo Point
    'geo_shape',            # Column 2 Geo Shape
    'year',                 # Column 3 Year
    'county_ID',            # Column 4 Län code
    'school_county',        # Column 5 Län name
    'municipality_ID',      # Column 6 Kommun code
    'school_municipality',  # Column 7 Kommun name
    'area_code',            # Column 8 ISO 3166-3 Area code
    'type',                 # Column 9 Type
    ]

# List of new names 
columns_to_drop = [
    'geo_point',            # Column 1 Geo Point
    'geo_shape',            # Column 2 Geo Shape
    'year',                 # Column 3 Year
    'area_code',            # Column 8 ISO 3166-3 Area code
    'type',                 # Column 9 Type
    ]

# Applying the new names 
kommun_data.columns = new_names

# Drop the specified columns
kommun_data.drop(columns=columns_to_drop, axis=1, inplace=True)

# Define the join keys
join_keys = ['school_municipality', 'municipality_ID']

# Apply merging and store the results back in the list
dataframes = [pd.merge(df, kommun_data, on=join_keys, how='left') for df in dataframes]

# Unpacking the list 
school_data_english, school_data_mathematics, school_data_swedish = dataframes

In [180]:
# Step 3 -  Imputing and dropping columns

# List of DataFrames
dataframes = [school_data_english, school_data_mathematics, school_data_swedish]

# Columns to fill via group-wise backward fill
columns_to_bfill = ['school_size', 'total_school_students', 'graduating_students']

# Define bins and labels for school size categorization
bins = [0, 49, 99, 199, 299, 399, 499, 599, 699, 799, 899, np.inf]
labels = ["1-49", "50-99", "100-199", "200-299", "300-399", "400-499", 
          "500-599", "600-699", "700-799", "800-899", "900-"]

# Define a list of columns to drop
columns_to_drop = [
    'total_school_students',
    'graduating_students',
    'total_fulltime_certified_teachers',
    'total_fulltime_teachers',                                           
    'share_fulltime_certified_teachers',                                    
    'total_active_teachers',                                            
    'total_active_certified_teachers',                                    
    ]

# For Loop 
for df in dataframes:
    # Step 1: Group-wise backward fill for specified columns
    df[columns_to_bfill] = df.groupby('school_ID')[columns_to_bfill].bfill()

    # Step 2: Categorize total_school_students into school_size
    df['school_size'] = pd.cut(
        df['total_school_students'].astype(float),  # Ensure numeric type
        bins=bins,
        labels=labels,
        right=True
    )

    # Dropping columns which will not be used
    df.drop(columns=columns_to_drop, axis=1, inplace=True)

In [181]:
# Step 4 -  Creating Variables 

# Preprocess Function
def preprocess_school_data(df, lang_suffix):
    """
    Preprocess a language-specific school dataset, retaining suffixes to allow merging.

    Parameters:
    - df: pandas DataFrame with subject-specific suffixes (e.g., '_sv')
    - lang_suffix: str, the suffix identifying the subject (e.g., 'sv', 'eng', 'ma')

    Returns:
    - Preprocessed DataFrame (language-specific columns retained)
    """

    # Drop language-specific share_students_A_E variable only
    df = df.drop(columns=[f'share_students_A_E_{lang_suffix}'], errors='ignore')

    # Difference in Difference variables
    df['treatment_year'] = np.where(df['academic_year'] == '2019/20', 1, 0)
    df['treatment_group'] = np.where(df['educational_stage'] == 'gymnasieskola', 1, 0)
    df['DiD'] = df['treatment_year'] * df['treatment_group']

    # Control variables
    df['private_ownership'] = np.where(df['type_of_ownership'] == 'Enskild', 1, 0)

    # Academic year processing
    df['academic_year'] = df['academic_year'].str[2:].astype('category')  # e.g., "2019/20" → "19/20"
    df['academic_year_spring'] = df['academic_year'].str.extract(r'/(\d{2})$').astype(int)

    # Categorical variables
    df['school_ID'] = df['school_ID'].astype('category')
    df['school_municipality'] = df['school_municipality'].astype('category')
    df['school_county'] = df['school_county'].astype('category')

    return df

school_data_swedish = preprocess_school_data(school_data_swedish, 'sv')
school_data_english = preprocess_school_data(school_data_english, 'eng')
school_data_mathematics = preprocess_school_data(school_data_mathematics, 'ma')

In [182]:
# Step 4 -  Full School DataFrame 

# Find the common school_IDs using set intersection
common_ids = set(school_data_english['school_ID']) \
             & set(school_data_swedish['school_ID']) \
             & set(school_data_mathematics['school_ID'])

# Filter each DataFrame to include only the common school_IDs
school_data_english = school_data_english[school_data_english['school_ID'].isin(common_ids)]
school_data_swedish = school_data_swedish[school_data_swedish['school_ID'].isin(common_ids)]
school_data_mathematics = school_data_mathematics[school_data_mathematics['school_ID'].isin(common_ids)]

# Extract relvant columns for matching 
math_F = school_data_mathematics[['school_ID', 'academic_year', 'share_students_F_ma']]
swedish_F = school_data_swedish[['school_ID', 'academic_year', 'share_students_F_sv']]
english_F = school_data_english[['school_ID', 'academic_year', 'share_students_F_eng']]

# Start from a full base dataset (any one of the three is fine)
school_data = school_data_english.drop(columns=['share_students_F_eng'])

# Merge Swedish share_students_F
school_data = school_data.merge(swedish_F, on=['school_ID', 'academic_year'], how='left')

# Merge English share_students_F
school_data = school_data.merge(english_F, on=['school_ID', 'academic_year'], how='left')

# Finally, merge back Mathematics
school_data = school_data.merge(math_F, on=['school_ID', 'academic_year'], how='left')
school_data

,school_ID,school_municipality,municipality_ID,type_of_ownership,academic_year,educational_stage,school_size,graduates_average_grade_points,share_female_students,share_foreign_background,...,county_ID,school_county,treatment_year,treatment_group,DiD,private_ownership,academic_year_spring,share_students_F_sv,share_students_F_eng,share_students_F_ma
0,74776778,Alingsås,1489,Kommunal,14/15,gymnasieskola,100-199,14.7,43.0,19.0,...,14,Västra Götalands län,0,1,0,0,15,0.0,2.3,0.0
1,18345915,Alingsås,1489,Kommunal,14/15,gymnasieskola,200-299,15.2,30.0,16.0,...,14,Västra Götalands län,0,1,0,0,15,0.0,0.0,0.0
2,68229719,Alingsås,1489,Kommunal,14/15,gymnasieskola,100-199,14.8,63.0,14.0,...,14,Västra Götalands län,0,1,0,0,15,0.0,0.0,0.0
3,61004230,Alingsås,1489,Kommunal,14/15,gymnasieskola,50-99,16.5,66.0,NaN,...,14,Västra Götalands län,0,1,0,0,15,0.0,0.0,2.3
4,71262305,Arboga,1984,Kommunal,14/15,gymnasieskola,100-199,15.5,50.0,13.0,...,19,Västmanlands län,0,1,0,0,15,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19435,50308658,Överkalix,2513,Kommunal,21/22,grundskola,100-199,11.4,45.0,25.0,...,25,Norrbottens län,0,0,0,0,22,31.2,25.0,NaN
19436,13342436,Överkalix,2513,Enskild,21/22,grundskola,50-99,NaN,44.0,NaN,...,25,Norrbottens län,0,0,0,1,22,NaN,NaN,NaN
19437,46252858,Övertorneå,2518,Enskild,21/22,grundskola,50-99,15.2,52.0,19.0,...,25,Norrbottens län,0,0,0,1,22,0.0,0.0,0.0
19438,90707437,Övertorneå,2518,Kommunal,21/22,grundskola,50-99,13.5,56.0,18.0,...,25,Norrbottens län,0,0,0,0,22,0.0,0.0,0.0
19439,18991431,Övertorneå,2518,Kommunal,21/22,grundskola,100-199,12.1,44.0,28.0,...,25,Norrbottens län,0,0,0,0,22,4.0,8.0,8.0

In [183]:
# Step 4 - Filtering for school_sizes with 1-49 students 

# Define the specific columns of interest; adjust these names as needed
selected_vars = ['graduates_average_grade_points', 
                 'share_female_students', 'share_foreign_background',
                 'share_postsecondary_parents', 'share_active_certified_teachers', 
                 'share_students_F_sv', 'share_students_F_eng', 'share_students_F_ma']

# Group by 'school_size_group' and compute the share of missing values
missing_share_by_group = school_data.groupby('school_size')[selected_vars].apply(lambda group: group.isna().mean())

# Generate the LaTeX table
latex_table = missing_share_by_group.to_latex(
    index=True,
    caption="Share of Missing Values by School Size Group",
    label="tab:missing_share_by_school_size",
    na_rep="0%",
    float_format="%.2f"  # This formats floats to two decimal places
)

# Filter out rows where school_size is '1-49'
school_data = school_data[school_data['school_size'] != '1-49']

/var/folders/dk/hpy2mtkd7sq6_2c3125100b80000gn/T/ipykernel_68528/1431191944.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  missing_share_by_group = school_data.groupby('school_size')[selected_vars].apply(lambda group: group.isna().mean())

In [ ]:
# Step 5 - Remove missing values

# List of columns to check for missing values
columns_to_check = [
    'graduates_average_grade_points',
    'share_active_certified_teachers',
    'share_postsecondary_parents',
    'share_foreign_background',
    'share_female_students', 
    'share_students_F_sv', 
    'share_students_F_eng',
    'share_students_F_ma']

# Drop rows where any of the specified columns have missing values
school_data = school_data.dropna(subset=columns_to_check)

In [ ]:
# Step 6 - Balancing my panel data

# Determine the total number of distinct academic years
n_periods = school_data['academic_year'].nunique()

# Balance the panel: keep only schools present in all academic years
school_data = school_data.groupby('school_ID').filter(lambda group: group['academic_year'].nunique() == n_periods)

In [ ]:
# Step 7 - Exporting 

# Defining the full path where the Excel file will be saved
pathname = '/Users/andrescruz/Documents/Handelshögskolan/MSc Economic/Semester 4/5350 Thesis in Economics/Processed Data/School_Data.xlsx'

# Exporting all the tables created into one Excel File 
with pd.ExcelWriter(pathname) as writer:
    school_data_english.to_excel(writer, sheet_name = 'English', index=False)
    school_data_mathematics.to_excel(writer, sheet_name = 'Mathematics', index=False)
    school_data_swedish.to_excel(writer, sheet_name = 'Swedish', index=False)
    school_data.to_excel(writer, sheet_name = 'All', index=False)